"use client";

import { useRef } from "react";
import InputField from "./InputField";
import Button from "../ui/Button";
import { useState } from "react";
import { studentSchema } from "../../schemas/student.schema.js";

export default function StudentForm({
  initialData = {},
  institutes = [],
  onSubmit,
  onCancel,
}) {
  const [errors, setErrors] = useState({});
  const photoRef = useRef(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    const formData = new FormData(e.target);
    const data = Object.fromEntries(formData.entries());

    // year as number or remove if blank
    if (data.year) data.year = Number(data.year);
    else delete data.year;

    try {
      await studentSchema.validate(data, { abortEarly: false });
      setErrors({});

      // attach photo file if selected
      if (photoRef.current?.files?.[0]) {
        data.studentPhoto = photoRef.current.files[0];
      }
      onSubmit(data);
    } catch (err) {
      const validationErrors = {};
      if (err.inner) {
        err.inner.forEach((e) => { validationErrors[e.path] = e.message; });
      } else {
        validationErrors[err.path] = err.message;
      }
      setErrors(validationErrors);
    }
  };

  return (
    <form
      onSubmit={handleSubmit}
      className="space-y-4 max-w-xl mx-auto bg-white p-6 rounded-2xl border border-orange-100 shadow-sm"
    >
      <h3 className="text-lg font-bold text-gray-800 border-b border-orange-50 pb-2">
        {initialData._id ? "Edit Student Profile" : "Register New Student"}
      </h3>

      <div className="grid grid-cols-2 gap-4">
        <InputField
          label="Full Name"
          name="full_name"
          placeholder="e.g. Priya Sharma"
          defaultValue={initialData.full_name}
          error={errors.full_name}
        />
        <InputField
          label="Roll Number"
          name="roll_no"
          placeholder="e.g. CS-2026-001"
          defaultValue={initialData.roll_no}
          error={errors.roll_no}
        />
      </div>

      <div className="grid grid-cols-2 gap-4">
        <InputField
          label="Enrollment No"
          name="enrollment_no"
          placeholder="e.g. EN2024001"
          defaultValue={initialData.enrollment_no}
          error={errors.enrollment_no}
        />
        <div>
          <label className="block mb-2 text-sm font-semibold text-gray-700">
            Institute <span className="text-orange-500">*</span>
          </label>
          <select
            name="institute_id"
            defaultValue={initialData.institute_id || ""}
            className={`w-full rounded-xl border bg-white text-black px-4 py-3 text-sm focus:outline-none ${
              errors.institute_id
                ? "border-red-500 focus:ring-2 focus:ring-red-200"
                : "border-orange-300 focus:border-orange-500 focus:ring-2 focus:ring-orange-200"
            }`}
          >
            <option value="" disabled>Select Institute</option>
            {institutes.map((c) => (
              <option key={c._id} value={c._id}>{c.institute_name}</option>
            ))}
          </select>
          {errors.institute_id && (
            <p className="mt-1 text-sm text-red-500">{errors.institute_id}</p>
          )}
        </div>
      </div>

      {/* Optional fields */}
      <div className="grid grid-cols-2 gap-4">
        <InputField
          label="Email (optional)"
          name="email"
          type="email"
          placeholder="student@example.com"
          defaultValue={initialData.email}
          error={errors.email}
        />
        <InputField
          label="Phone (optional)"
          name="phone"
          placeholder="10-digit number"
          defaultValue={initialData.phone}
          error={errors.phone}
        />
      </div>

      <div className="grid grid-cols-3 gap-4">
        <InputField
          label="Batch (optional)"
          name="batch"
          placeholder="e.g. 2024-2026"
          defaultValue={initialData.batch}
          error={errors.batch}
        />
        <InputField
          label="Stream (optional)"
          name="course"
          placeholder="e.g. Computer Science"
          defaultValue={initialData.course}
          error={errors.course}
        />
        <InputField
          label="Year (optional)"
          name="year"
          type="number"
          placeholder="e.g. 1"
          defaultValue={initialData.year}
          error={errors.year}
        />
      </div>

      <div>
        <label className="block mb-2 text-sm font-semibold text-gray-700">
          Photo (optional)
        </label>
        <input
          ref={photoRef}
          type="file"
          accept="image/*"
          className="w-full border border-orange-200 rounded-xl px-3 py-2 text-sm"
        />
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-800 font-semibold">
        Password is auto-generated by the backend as: <code className="font-mono bg-amber-100 px-1 rounded">institute_code + enrollment_no</code>. It will be shown once in the response.
      </div>

      <div className="flex justify-end gap-3 pt-4 border-t border-orange-50">
        <Button variant="secondary" onClick={onCancel}>Cancel</Button>
        <Button type="submit">Save Student</Button>
      </div>
    </form>
  );
}
