"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import Swal from "sweetalert2";
import AdminLayout from "../../layouts/AdminLayout";
import StudentForm from "../../components/form/StudentForm";
import { createStudent } from "../../services/student";
import { getInstitutes } from "../../services/institute";

export default function NewStudentPage() {
  const router = useRouter();
  const [institutes, setInstitutes] = useState([]);

  useEffect(() => {
    getInstitutes()
      .then((res) => {
        const list = res.data?.data || res.data || [];
        setInstitutes(Array.isArray(list) ? list : []);
      })
      .catch(() => {});
  }, []);

  const handleSubmit = async (data) => {
    try {
      const res = await createStudent(data);
      const created = res.data?.data || res.data;

      if (created?.generated_password) {
        await Swal.fire({
          icon: "success",
          title: "Student Registered",
          html: `
            <p class="text-sm text-slate-600 mb-2"><strong>${created.full_name}</strong></p>
            <div class="bg-red-50 border border-red-200 rounded p-2 mb-2 text-xs text-red-700 font-bold">
              ⚠ Password shown ONCE — save it now.
            </div>
            <div class="bg-orange-50 border border-orange-200 rounded p-3">
              <p class="text-xs text-slate-500 mb-1">Generated Password</p>
              <p class="font-mono font-black text-orange-700 text-xl">${created.generated_password}</p>
            </div>
          `,
          confirmButtonText: "I have saved the password",
        });
      } else {
        Swal.fire({ icon: "success", title: "Student Registered", timer: 1500, showConfirmButton: false });
      }
      router.push("/students");
    } catch (err) {
      Swal.fire({
        icon: "error",
        title: "Registration Failed",
        text: err?.response?.data?.message || err.message,
      });
    }
  };

  return (
    <AdminLayout>
      <div className="space-y-6">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Register Student</h2>
          <p className="text-sm text-slate-500">
            Add a new student. Their login password will be auto-generated by the backend.
          </p>
        </div>
        <div className="bg-white p-8 rounded-2xl border border-slate-200 shadow-lg">
          <StudentForm
            institutes={institutes}
            onSubmit={handleSubmit}
            onCancel={() => router.push("/students")}
          />
        </div>
      </div>
    </AdminLayout>
  );
}
